apiVersion: argoproj.io/vqalpha1
kind: Application
metadata:
    name: stage-root-application
spec:
    source:
        repoURL: https://github.com/your-org/gitops.git
        targetRevision: main
        path: architectures/AppOfApps/stage
    destination:
        server: https://stage-kubernetes.default.svc
        namespace: argocd

    syncPlicy:
        automated:
            prune: true
            selfHeal: true
        
        syncOptions:
            - CreateNamespace=true
