replicaCount: 3

image:
  repository: 758854589827.dkr.ecr.us-east-1.amazonaws.com/dev/eks-python-app
  tag: 25-a1b2c3d4
  policy: IfNotPresent

nameOverride: ""
fullNameOverride: ""

serviceAccount:
    create: true
    name: ""

service:
  port: 80
  targetPort: 8080
  type: ClusterIP

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: true
  path: /health/live
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  enabled: true
  path: /health/ready
  initialDelaySeconds: 5
  periodSeconds: 10

podAnnotations: {}

podLabels: {}

nodeSelector: {}

tolerations: {}

affinity: {}

