apiVersion: argoproj.io/vqalpha1
kind: Application
metadata:
    name: dev-app1
    namespace: argocd
    labels:
        environment: dev
        app: dev1
        team: devops
spec:
    project: dev
    source:
        repoURL: https://github.com/your-org/gitops.git
        targetRevision: main
        path: charts/app1
    helm:
        releaseName: app1-dev
        valuesFiles:
            - ../../values/dev/app1-values.yaml
    destination:
        server: https://dev-kubernetes.default.svc
        namespace: argocd

    syncPlicy:
        automated:
            prune: true
            selfHeal: true
        
        syncOptions:
            - CreateNamespace=true